import PropTypes from 'prop-types';
import { useState } from 'react';

// material-ui
import { styled, useTheme } from '@mui/material/styles';
import { Avatar, Box, Grid, Menu, MenuItem, Paper, Typography, Card } from '@mui/material';

// project imports
import MainCard from 'ui-component/cards/MainCard';




const CardWrapper = styled(Paper)(({ theme }) => ({
    backgroundColor: '#fff',
    color: '#868686',
    overflow: 'hidden',
    position: 'relative',
    '&:after': {
        content: '""',
        position: 'absolute',
        width: 210,
        height: 210,
        background: theme.palette.secondary[800],
        borderRadius: '50%',
        top: -85,
        right: -95,
        [theme.breakpoints.down('sm')]: {
            top: -105,
            right: -140
        }
    },
    '&:before': {
        content: '""',
        position: 'absolute',
        width: 210,
        height: 210,
        background: theme.palette.secondary[800],
        borderRadius: '50%',
        top: -125,
        right: -15,
        opacity: 0.5,
        [theme.breakpoints.down('sm')]: {
            top: -155,
            right: -70
        }
    }
}));

const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    padding: theme.spacing(1),
    // textAlign: 'center',
    color: '#000',
}));


const Layout = () => {
    const theme = useTheme();

    return (
        <>
            <Paper border="false" content="false" >
                <Grid container item xs={12} md={7} lg={8} spacing={1}>
                    <Grid item xs={12} md={5} lg={4}>
                        <Item>
                            <Box
                                id="category-a"
                                sx={{ fontSize: '12px', textTransform: 'uppercase' }}
                            >
                                <Typography textAlign={'center'} >Ask Media Dev</Typography>
                            </Box>
                            <Box aria-labelledby="category-a" sx={{ pl: 2 }}>

                                The ASK MEDIA DEV platform provides services, tools, and information generated by AI tools.
                                Our platform is free to use.

                            </Box>
                        </Item>
                    </Grid>
                    <Grid item xs={6} lg={3}>
                        <Item>
                            <Box
                                id="category-b"
                                sx={{ fontSize: '12px', textTransform: 'uppercase' }}
                            >
                                <Typography textAlign={'center'}>Legal</Typography>

                            </Box>
                            <Box component="ul" aria-labelledby="category-b" sx={{ pl: 2 }}>
                                <li> Terms of Use </li>
                                <li> Privacy Policy </li>
                                <li> Copyright Policyt </li>
                            </Box>
                        </Item>
                    </Grid>
                    <Grid item xs={6} lg={3}>
                        <Item>
                            <Typography textAlign={'center'}>Resources</Typography>
                            <Box component="ul" aria-labelledby="category-c" sx={{ pl: 2 }}>
                                <li> ASK CHAT GPT</li>
                                <li> ASK DALL·E 2</li>
                                <li> ASK PLAYGROUND</li>
                            </Box>
                        </Item>
                    </Grid>
                    <Grid item xs={6} lg={3}>
                        <Item>
                            <Box textAlign={'center'}
                                id="category-d"
                                sx={{ fontSize: '12px', textTransform: 'uppercase' }}
                            >
                                Topic 5
                            </Box>
                            <Box component="ul" aria-labelledby="category-d" sx={{ pl: 2 }}>
                                <li>Subtopic 4.1</li>
                                <li>Subtopic 4.2</li>
                                <li>Subtopic 4.3</li>
                            </Box>
                        </Item>
                    </Grid>
                </Grid>
                <Grid
                    item
                    xs={12}
                    container
                    justifyContent="space-between"
                    alignItems="center"
                    flexDirection={{ xs: 'column', sm: 'row' }}
                    sx={{ fontSize: '12px' }}
                >
                    <Grid container columnSpacing={1} sx={{ order: { xs: 1, sm: 2 } }}>
                        <Grid>
                            <Item>Link A</Item>
                        </Grid>
                        <Grid>
                            <Item>Link B</Item>
                        </Grid>
                        <Grid>
                            <Item>Link C</Item>
                        </Grid>
                    </Grid>
                </Grid>
            </Paper>

        </>
    );
};



export default Layout;
